_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 128
dataset_file:
    value: /media/rp/Elements/abhay_ws/mujoco_contact_graph_generation/results/data_v5/processed_data/state_hist_all.csv
device:
    value: cuda
epochs:
    value: 1000
learning_rate:
    value: 0.01
log_freq:
    value: 10
name:
    value: wrench_to_contact_type_v1
save_model:
    value: true
seed:
    value: 42
wandb:
    value: true
wandb_entity:
    value: abhay-negi-usc
wandb_key:
    value: af3eeeb1c9d72d3a76a00b58af7e341d8540ed1b
wandb_project:
    value: contact_classification
weight_decay:
    value: 0.0001
